services:
  app:
    ports:
      - 5000:5000
      - 8080:8080
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      mongodb:
        condition: service_healthy
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
      - MONGO_INITDB_DATABASE=questionnaire
    ports:
      - 27017:27017
    volumes:
      - mongodb-volume:/data/db
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mongosh", "--username admin --password 123", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:123@mongodb:27017/
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb-volume: